version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  redis:
    image: "redis:alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672" 
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  nginx:
    image: "nginx:latest"
    ports:
      - "3000:80"
    depends_on:
      - user-service
      - product-service
      - cart-service

