name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push User Service
        uses: docker/build-push-action@v2
        with:
          context: ./user-service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest

      - name: Build and push Product Service
        uses: docker/build-push-action@v2
        with:
          context: ./product-service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/product-service:latest

      - name: Build and push Order Service
        uses: docker/build-push-action@v2
        with:
          context: ./order-service
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/order-service:latest

      - name: Build and push nginx
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nginx:latest
